name: CI

permissions:
  pull-requests: write

on:
  pull_request_target:
    branches: [main]

jobs:
  auto-assigner:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: toshimaru/auto-author-assign@v2.1.1

      - name: Print workflow mode
        run: echo "Running from base repo (pull_request_target)"

  pre-commit:
    runs-on: ubuntu-latest
    needs: auto-assigner

    steps:
      - name: Checkout PR code safely (fork or local)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref:        ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Dummy lint step
        run: |
          echo "Running CI..."
          python --version
